Metrics/MethodLength:
  Max: 20

Style/AndOr:
  EnforcedStyle: conditionals

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'

Style/SignalException:
  EnforcedStyle: semantic

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
